name: to deploy app backend
on:
  push:
    branches:
      - main

jobs:
  
  build_jar:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: install java
        uses: actions/setup-java@v4.7.1
        with:
          distribution: 'temurin' 
          java-version: '17'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: build_jar
        run: |
          cd /home/runner/work/eventmanagement_backend/eventmanagement_backend
          mvn clean package -DskipTests
          cd ./target
          ls -lrt

      - name: jar upload
        uses: actions/upload-artifact@v4.6.2
        with:
          name: todobackendjarfile
          path: /home/runner/work/eventmanagement_backend/eventmanagement_backend/target/EventManagement-0.0.1-SNAPSHOT.jar
          if-no-files-found: error
          retention-days: 7


  dockerimage:
    needs: build_jar
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo
        uses: actions/checkout@v4

      - name: jar download
        uses: actions/download-artifact@v4.3.0
        with:
          name: todobackendjarfile
          path: /home/runner/work/eventmanagement_backend/eventmanagement_backend

      - name: login to dockerhub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: setup build
        uses: docker/setup-buildx-action@v3

      - name: build & push
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_TAG }}:latest

  # invokerender:
  #   needs: dockerimage
  #   runs-on: ubuntu-latest
  #   steps:

  #     - name: Trigger Render deploy
  #       run: |
  #         curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
  #         sleep 30
  #         echo " service deployed on render at https://sri-todo.onrender.com "


      
    
      


    
